apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
images:
- name: fluxcd/source-controller
  newName: diptipaiacr1.azurecr.io/source-controller
  newTag: v0.4
patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller
      labels:
        azure.workload.identity/use: "true"
    spec:
      template:
        metadata:
          labels:
            azure.workload.identity/use: "true"
  target:
    kind: Deployment
    name: (source-controller)
